### ISSUE TITLE
Weekly aggregation and delivery of news

### ISSUE THREAD

**Issue by bradgessler** [legiblenews/community#1]
Various people have requested a weekly view of the news from email inquiries to me and at https://news.ycombinator.com/item?id=28651142

Build out a view of the news’s that aggregates the weeks events into one view. The view should be accessible by day and by category.

**Comment by bradgessler** [comment]
@matthewmiaow I've got a beta running for this at http://beta.legiblenews.com/week that you can check out.

A few things that I think are issues that I'm working through:
- [ ] First-level headers group properly, but sub-headers don't. For example, you'll see Covid-19 repeated multiple times per week. I need to do some work to de-duplicate sub-headings.
- [ ] The H1 header still needs a lot of work. I'm not please with the copy and typography at the moment.

Feedback would be much appreciated!

**Comment by matthewmiaow** [comment]
Thanks for sharing!

I made a quick mock-up of a possible H1 header for the weekly edition, inspired by old-timey print news. Don't know if it's one too many fonts to load however. 
![mastheadlegiblenewsmock](https://user-images.githubusercontent.com/84684364/145729858-687e217a-0359-4f52-955c-acbbd88807cc.png)
Otherwise, I think you could make "Legible News" the h1 header, and keep the "48th edition" in the subtitle beneath, maybe?
Cheers!

**Comment by bradgessler** [comment]
Thanks for taking a crack at it! I am trying to keep fonts down (in the name of speed, both loading fonts and visually) and landed on this:

<img width="989" alt="Screen Shot 2021-12-16 at 00 48 18" src="https://user-images.githubusercontent.com/4628/146338467-50358cb1-8a05-4e91-8067-ba1423b4ae9b.png">

There's still some room for improvement, so I'll keep playing around with it and tweaking.

**Comment by maxdesalle** [comment]
Any updates on this @bradgessler? Just subscribed to Legible News Plus and would love to get access to this email digest.

**Comment by bradgessler** [comment]
Working on it at the moment! I'm going to be rolling out user accounts, then after that the email digest will follow.

I could use your help to clarify a requirement: would you want weekly emails, daily, or both?

**Comment by maxdesalle** [comment]
Awesome! The ability to have both would be great.

I suppose if you have daily emails set up you will not want the weekly emails, and if you have the weekly emails setup you will not want the daily emails. So you should probably be able to toggle on/off the daily emails and the weekly emails separately.

**Comment by bradgessler** [comment]
Yeah good point about not wanting both. If I go down that route the setting would probably look something like this:

```
Email updates
=============
(*) None
( ) Daily
( ) Weekly
```

We'll see if somebody else chimes in with a more concrete reason for wanting both. I could see going either way on that.

Thanks again for your input! 🙏

**Comment by bradgessler** [comment]
Started work on this feature, which requires reforming the inputs of the article content into something that can be "flattened" for email and so that it can be more intelligently grouped for weekly updates. The plus side? For Daily comments I can now better group headlines with content:

<img width="1392" alt="Screen Shot 2022-04-04 at 14 04 18" src="https://user-images.githubusercontent.com/4628/161631985-3718838b-0eb9-4735-828a-758689735ead.png">

I have to cleanup some code after getting this view working, then update the "weekly" view to group via subtitles (currently it only groups via the 1st level title).

Once I get those two tasks squared away I'll start playing around with email delivery 🤠 📫

**Comment by bradgessler** [comment]
Good news! You thought it was going to be about code, but it's a personal announcement: third baby girl was born safely last week and her and mom are doing smitten.

On the news front, I shipped the screen above to https://legiblenews.com/week so the categorization is in a much better spot. Email work will be starting, which will take some time as I adjust to having kids++ and wrestle with email formatting a bit. For now enjoy the weekly edition online and LMK if you have any feedback on the appearance or organization of sections.

**Comment by maxdesalle** [comment]
Congratulations @bradgessler! Happy for you.

Looking forward to the new email feature.

**Comment by bradgessler** [comment]
Here's the first few screenshots of the weekly email digest.

### Gmail
<img width="1271" alt="Screen Shot 2022-05-03 at 16 42 52" src="https://user-images.githubusercontent.com/4628/166594612-91cf277b-1974-4d11-8b0d-3f31f9efe99a.png">

### Mail app on iPhone
![IMG_1670AD75DD49-1](https://user-images.githubusercontent.com/4628/166595674-5ece88fb-9695-403c-9652-04e35b326037.jpeg)

HTML in email is a bit of a pain, but necessary for linking to contextual content.

What email clients are folks planning on using to read weekly email digests? I'll prioritize making this look decent on those clients first.

**Comment by maxdesalle** [comment]
The email in the email iPhone app looks really great! I'm using the [ProtonMail](https://protonmail.com) web app.

**Comment by bradgessler** [comment]
Alrighty, I've got a test page at https://legiblenews.com/issue_email_deliveries that I'd like for folks to head to and try to make sure it renders reasonably well in their email client. **Note that when you click "Send test email" it will be a bit slow** so please refrain from clicking on it a bunch of times. There's several optimizations I have to make to speed this up after I can get a few people to test this out in their email clients.

Here's about how long it takes to generate and send the email currently:

https://user-images.githubusercontent.com/4628/166862980-e29e8743-d972-452e-b70e-c779a877a792.mov

This will be sped up to be instant.

@maxdesalle could I trouble you to send an issue to your ProtonMail app and post a screenshot here? I also welcome your feedback on whether or not it looks reasonable.

**Comment by maxdesalle** [comment]
Looks great on my end! Simple and clean.

![CleanShot 2022-05-05 at 06 47 58@2x](https://user-images.githubusercontent.com/70470326/166865060-ae639bfc-e0ea-4ca9-ad91-efb2d6b22658.png)

**Comment by bradgessler** [comment]
Woohoo! Awesome. I'll start wiring up the UI that makes this work and speed it up.

**Comment by bradgessler** [comment]
Gmail iOS app looks OK. In general I've noticed Gmail truncates really long HTML messages, so the week subscriptions don't look great.

https://user-images.githubusercontent.com/4628/166865860-ae66442e-94a8-4140-9a7e-99f17c3ca9a1.MOV

**Comment by bradgessler** [comment]
Alrighty ... I've finally got the daily and weekly subscriptions working at https://legiblenews.com/email_subscription. Here's what it looks like:

https://user-images.githubusercontent.com/4628/168450096-9fa8b5cf-45be-464e-98ce-ca60d19829b8.mov

If you try to unsubscribe, there's currently a bug that will display an error, but it will unsubscribe despite the error message.

Give it a whirl and please give feedback! I'm at a point now where I'm going to clean up the last few bugs, polish the feature, and refactor a few things so its more stable.

**Comment by bradgessler** [comment]
Unsubscription issues are sorted out. There's still some issues with dates I'm working through that appear during the initial subscription. What does that mean to you?

1. [x] You might get 2 deliveries in one day. You may also get 0 deliveries in one day. TBH this is a bit embarrassing, but egos are lame so I'd rather ship this stuff now and just be upfront about it. I'm going to add a bunch of back-end features that make it easy for me to confirm the correct deliveries went out and also make it easier for you to see what has been delivered to you (and what will be delivered to you in the future).
2. [ ] I'll be adding links to the email that make for 1-click email unsubscriptions. I also think I have to add some legal stuff at the bottom of the email to make it clear to subscribers who is sending them the email, that its not spam, and give them easy ways to unsubscribe.

I'm hoping to have all of this stuff squared away over the next few weeks so I can finally close out this ticket :-) As always, hit me back with any concerns, feedback, or feature requests. Best to strike while the iron is hot!

**Comment by maxdesalle** [comment]
>  You might get 2 deliveries in one day. You may also get 0 deliveries in one day. TBH this is a bit embarrassing, but egos are lame so I'd rather ship this stuff now and just be upfront about it. I'm going to add a bunch of back-end features that make it easy for me to confirm the correct deliveries went out and also make it easier for you to see what has been delivered to you (and what will be delivered to you in the future).

I subscribed to the weekly email last Sunday, and got one email yesterday evening and one email this morning. When are weekly issues supposed to be sent out?

**Comment by bradgessler** [comment]
@maxdesalle I don't know how, but I missed your message notification. I've been subscribed to the daily sub for a few months and have that working. Just switched it up to the weekly sub to see how that's working out.

The weekly sub should deliver each Saturday at midnight UTC. That could be Friday depending on your time zone.

Let me know if you're still having trouble with delivery if the weekly digests.

**Comment by bradgessler** [comment]
After a month of receiving weekly issues, I haven't run into any problems with deliver so I'm marking that issue as closed.

For me in PT I get the weekly edition delivered Friday at 5p.
