### ISSUE TITLE
Body in heading

### ISSUE THREAD

**Issue by Ekstropiya** [legiblenews/community#6]
The front page currently shows the body for "2021-22 European windstorm season" in the heading, for example:

### 2021–22 European windstorm season At least nine people are killed in Belgium, Ireland, the Netherlands, Poland and the United Kingdom as Storm Eunice impacts northwestern Europe. (BBC News) (Dutch News) (Euronews) England records a record wind gust of 122 mph (196 kmh) on the Isle of Wight in the English Channel. (Reuters) The Grain Power Station in Kent, England, goes offline following the collapse of one of its towers and the roof of The O2 Arena in London is severely damaged due to high winds. (BBC News) (ITV News) The roof of the ADO Den Haag Stadium, in The Hague, the Netherlands, is severely damaged. (The Guardian)

**Comment by bradgessler** [comment]
Do you have a URL or screenshot? I tried https://legiblenews.com/, https://legiblenews.com/yesterday , and https://legiblenews.com/2-days-ago but couldn't reproduce.

If you can't reproduce, I'd guess a cache was wiped out and new content was pulled through.

**Comment by Ekstropiya** [comment]
The issue was on the page for the 18th (atm, https://legiblenews.com/3-days-ago) under Disasters and accidents. It does look like it's fixed, so I'll close the issue. Thanks.

**Comment by bradgessler** [comment]
If you run into a similar issue, please open another issue even if it resolves itself. I'll build a "report a rendering error" feature that saves the cache so I can reproduce it later if it happens frequently.

Thanks so much for reporting!
